[package]
name = "life-in-2-dimensions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
bevy_rapier2d = { version = "0.21.0", features = ["debug-render-2d"] }
