name: build
on:
    push:
        branches:
            - main

env:
    binary-name: life-in-2-dimensions
jobs:
    build-windows:
        runs-on: windows-2022
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: install Rust 1.69.0
              uses: actions-rs/toolchain@v1
              with:
                  target: x86_64-pc-windows-msvc
                  toolchain: 1.69.0
            - name: build
              run: cargo build -r --target x86_64-pc-windows-msvc
            - name: r
              run: |
                  mkdir windows
                  mv target/x86_64-pc-windows-msvc/release/${{ env.binary-name }}.exe windows/${{ env.binary-name }}.exe
                  mv assets windows/assets
            - name: upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: Windows Build
                  path: windows
